// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: diagnostics/diagnostics.proto

package diagnostics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiagnosticsService_GetDiagnostics_FullMethodName = "/diagnostics.DiagnosticsService/GetDiagnostics"
)

// DiagnosticsServiceClient is the client API for DiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Diagnostics service provides service dependency and connection status information
type DiagnosticsServiceClient interface {
	// Get diagnostic information about service dependencies
	GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error)
}

type diagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticsServiceClient(cc grpc.ClientConnInterface) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{cc}
}

func (c *diagnosticsServiceClient) GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiagnosticsResponse)
	err := c.cc.Invoke(ctx, DiagnosticsService_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServiceServer is the server API for DiagnosticsService service.
// All implementations must embed UnimplementedDiagnosticsServiceServer
// for forward compatibility.
//
// Diagnostics service provides service dependency and connection status information
type DiagnosticsServiceServer interface {
	// Get diagnostic information about service dependencies
	GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error)
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

// UnimplementedDiagnosticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagnosticsServiceServer struct{}

func (UnimplementedDiagnosticsServiceServer) GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedDiagnosticsServiceServer) mustEmbedUnimplementedDiagnosticsServiceServer() {}
func (UnimplementedDiagnosticsServiceServer) testEmbeddedByValue()                            {}

// UnsafeDiagnosticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticsServiceServer will
// result in compilation errors.
type UnsafeDiagnosticsServiceServer interface {
	mustEmbedUnimplementedDiagnosticsServiceServer()
}

func RegisterDiagnosticsServiceServer(s grpc.ServiceRegistrar, srv DiagnosticsServiceServer) {
	// If the following call panics, it indicates UnimplementedDiagnosticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagnosticsService_ServiceDesc, srv)
}

func _DiagnosticsService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticsService_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).GetDiagnostics(ctx, req.(*GetDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagnosticsService_ServiceDesc is the grpc.ServiceDesc for DiagnosticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagnosticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diagnostics.DiagnosticsService",
	HandlerType: (*DiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiagnostics",
			Handler:    _DiagnosticsService_GetDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagnostics/diagnostics.proto",
}
