// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: diagnostics/diagnostics.proto

package diagnostics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for diagnostic information
type GetDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsRequest) Reset() {
	*x = GetDiagnosticsRequest{}
	mi := &file_diagnostics_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequest) ProtoMessage() {}

func (x *GetDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_diagnostics_diagnostics_proto_rawDescGZIP(), []int{0}
}

// Response containing diagnostic information
type GetDiagnosticsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of service name to dependency status
	Services      map[string]*ServiceDependency `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsResponse) Reset() {
	*x = GetDiagnosticsResponse{}
	mi := &file_diagnostics_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResponse) ProtoMessage() {}

func (x *GetDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_diagnostics_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDiagnosticsResponse) GetServices() map[string]*ServiceDependency {
	if x != nil {
		return x.Services
	}
	return nil
}

// ServiceDependency represents the status of a dependency on another service
type ServiceDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address of the service (if known)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Connection state
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Serving status
	Serving string `protobuf:"bytes,3,opt,name=serving,proto3" json:"serving,omitempty"`
	// Last time this dependency was checked (UNIX timestamp)
	LastChecked int64 `protobuf:"varint,4,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	// Additional diagnostic details (flexible key-value pairs)
	Details       map[string]string `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDependency) Reset() {
	*x = ServiceDependency{}
	mi := &file_diagnostics_diagnostics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDependency) ProtoMessage() {}

func (x *ServiceDependency) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_diagnostics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDependency.ProtoReflect.Descriptor instead.
func (*ServiceDependency) Descriptor() ([]byte, []int) {
	return file_diagnostics_diagnostics_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceDependency) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceDependency) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ServiceDependency) GetServing() string {
	if x != nil {
		return x.Serving
	}
	return ""
}

func (x *ServiceDependency) GetLastChecked() int64 {
	if x != nil {
		return x.LastChecked
	}
	return 0
}

func (x *ServiceDependency) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_diagnostics_diagnostics_proto protoreflect.FileDescriptor

const file_diagnostics_diagnostics_proto_rawDesc = "" +
	"\n" +
	"\x1ddiagnostics/diagnostics.proto\x12\vdiagnostics\"\x17\n" +
	"\x15GetDiagnosticsRequest\"\xc4\x01\n" +
	"\x16GetDiagnosticsResponse\x12M\n" +
	"\bservices\x18\x01 \x03(\v21.diagnostics.GetDiagnosticsResponse.ServicesEntryR\bservices\x1a[\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.diagnostics.ServiceDependencyR\x05value:\x028\x01\"\x83\x02\n" +
	"\x11ServiceDependency\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\aserving\x18\x03 \x01(\tR\aserving\x12!\n" +
	"\flast_checked\x18\x04 \x01(\x03R\vlastChecked\x12E\n" +
	"\adetails\x18\x05 \x03(\v2+.diagnostics.ServiceDependency.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012o\n" +
	"\x12DiagnosticsService\x12Y\n" +
	"\x0eGetDiagnostics\x12\".diagnostics.GetDiagnosticsRequest\x1a#.diagnostics.GetDiagnosticsResponseB4Z2git.sonicoriginal.software/grpc-protos/diagnosticsb\x06proto3"

var (
	file_diagnostics_diagnostics_proto_rawDescOnce sync.Once
	file_diagnostics_diagnostics_proto_rawDescData []byte
)

func file_diagnostics_diagnostics_proto_rawDescGZIP() []byte {
	file_diagnostics_diagnostics_proto_rawDescOnce.Do(func() {
		file_diagnostics_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diagnostics_diagnostics_proto_rawDesc), len(file_diagnostics_diagnostics_proto_rawDesc)))
	})
	return file_diagnostics_diagnostics_proto_rawDescData
}

var file_diagnostics_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_diagnostics_diagnostics_proto_goTypes = []any{
	(*GetDiagnosticsRequest)(nil),  // 0: diagnostics.GetDiagnosticsRequest
	(*GetDiagnosticsResponse)(nil), // 1: diagnostics.GetDiagnosticsResponse
	(*ServiceDependency)(nil),      // 2: diagnostics.ServiceDependency
	nil,                            // 3: diagnostics.GetDiagnosticsResponse.ServicesEntry
	nil,                            // 4: diagnostics.ServiceDependency.DetailsEntry
}
var file_diagnostics_diagnostics_proto_depIdxs = []int32{
	3, // 0: diagnostics.GetDiagnosticsResponse.services:type_name -> diagnostics.GetDiagnosticsResponse.ServicesEntry
	4, // 1: diagnostics.ServiceDependency.details:type_name -> diagnostics.ServiceDependency.DetailsEntry
	2, // 2: diagnostics.GetDiagnosticsResponse.ServicesEntry.value:type_name -> diagnostics.ServiceDependency
	0, // 3: diagnostics.DiagnosticsService.GetDiagnostics:input_type -> diagnostics.GetDiagnosticsRequest
	1, // 4: diagnostics.DiagnosticsService.GetDiagnostics:output_type -> diagnostics.GetDiagnosticsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_diagnostics_diagnostics_proto_init() }
func file_diagnostics_diagnostics_proto_init() {
	if File_diagnostics_diagnostics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diagnostics_diagnostics_proto_rawDesc), len(file_diagnostics_diagnostics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diagnostics_diagnostics_proto_goTypes,
		DependencyIndexes: file_diagnostics_diagnostics_proto_depIdxs,
		MessageInfos:      file_diagnostics_diagnostics_proto_msgTypes,
	}.Build()
	File_diagnostics_diagnostics_proto = out.File
	file_diagnostics_diagnostics_proto_goTypes = nil
	file_diagnostics_diagnostics_proto_depIdxs = nil
}
